#
#   Library: bosco
#
set (LIB_SOURCES ${LIB_SOURCES} .lib/bosco/src/AbstractGame.gs)
set (LIB_SOURCES ${LIB_SOURCES} .lib/bosco/src/Bag.gs)
set (LIB_SOURCES ${LIB_SOURCES} .lib/bosco/src/ECS/CoreTest.vala)
set (LIB_SOURCES ${LIB_SOURCES} .lib/bosco/src/ECS/EntityBase.gs)
set (LIB_SOURCES ${LIB_SOURCES} .lib/bosco/src/ECS/EntityPool.vala)
set (LIB_SOURCES ${LIB_SOURCES} .lib/bosco/src/ECS/Exceptions.gs)
set (LIB_SOURCES ${LIB_SOURCES} .lib/bosco/src/ECS/Group.gs)
set (LIB_SOURCES ${LIB_SOURCES} .lib/bosco/src/ECS/Matcher.gs)
set (LIB_SOURCES ${LIB_SOURCES} .lib/bosco/src/ECS/WorldBase.gs)
set (LIB_SOURCES ${LIB_SOURCES} .lib/bosco/src/Events/ComponentReplaced.gs)
set (LIB_SOURCES ${LIB_SOURCES} .lib/bosco/src/Events/EntityChanged.gs)
set (LIB_SOURCES ${LIB_SOURCES} .lib/bosco/src/Events/EntityReleased.gs)
set (LIB_SOURCES ${LIB_SOURCES} .lib/bosco/src/Events/GroupChanged.gs)
set (LIB_SOURCES ${LIB_SOURCES} .lib/bosco/src/Events/GroupUpdated.gs)
set (LIB_SOURCES ${LIB_SOURCES} .lib/bosco/src/Events/GroupsChanged.gs)
set (LIB_SOURCES ${LIB_SOURCES} .lib/bosco/src/Events/WorldChanged.gs)
set (LIB_SOURCES ${LIB_SOURCES} .lib/bosco/src/Interfaces/IComponent.vala)
set (LIB_SOURCES ${LIB_SOURCES} .lib/bosco/src/Interfaces/IMatcher.vala)
set (LIB_SOURCES ${LIB_SOURCES} .lib/bosco/src/Interfaces/ISystem.vala)
set (LIB_SOURCES ${LIB_SOURCES} .lib/bosco/src/Sprite.gs)
set (LIB_SOURCES ${LIB_SOURCES} .lib/bosco/src/Version.gs)
